Fix regression in article preview
Fatal error: Call to a member function getCategoryById() on null in
D:\xampp\htdocs\master\application\modules\article\views\index\show.php
on line 7

Fatal error: Call to a member function getCountComments() on null in
D:\xampp\htdocs\master\application\modules\article\views\index\show.php
on line 14